Repository deepchecks/monitoring, pull requests merged in 2023-06, with the labels that each got.

#156 no models found message fix
  frontend/src/components/NoResults.tsx
  frontend/src/pages/ModelsPage.tsx
Labels: invalid

#163 [MON-2347] Alert link fix
  backend/deepchecks_monitoring/ee/integrations/slack.py
  backend/deepchecks_monitoring/notifications.py
  backend/deepchecks_monitoring/schema_models/alert_webhook.py
  backend/deepchecks_monitoring/utils/alerts.py
Labels: bug

#164 analysis range correction
  frontend/src/components/Analysis/AnalysisItem/helpers/manipulateAnalysisItem.ts
Labels: invalid

#162 subscription state not updating
  backend/deepchecks_monitoring/ee/api/v1/billing.py
Labels: bug

#159 Models view all
  backend/deepchecks_monitoring/api/v1/model.py
  backend/deepchecks_monitoring/ee/api/v1/members.py
  backend/deepchecks_monitoring/utils/auth.py
  backend/tests/api/test_models.py
  backend/tests/common.py
  frontend/src/api/generated.ts
  frontend/src/components/WorkspaceSettings/components/Members/components/AssignModels.tsx
  frontend/src/components/WorkspaceSettings/components/ModelsTab/ModelsTab.tsx
  frontend/src/helpers/hooks/useModels.tsx
Labels: enhancement

#173 assign models hotfix
  frontend/src/components/WorkspaceSettings/components/Members/components/AssignModels.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/MembersTable/MembersTable.tsx
  frontend/src/components/WorkspaceSettings/components/ModelsTab/ModelsTab.tsx
Labels: bug, invalid

#183 fix_stripe_401
  backend/deepchecks_monitoring/ee/api/v1/billing.py
Labels: bug

#147 Jonatan/mon 2301 improved model data alerts
  backend/deepchecks_monitoring/api/v1/__init__.py
  backend/deepchecks_monitoring/api/v1/alert_rule.py
  backend/deepchecks_monitoring/api/v1/configuration.py
  backend/deepchecks_monitoring/api/v1/data_ingestion_alert.py
  backend/deepchecks_monitoring/api/v1/data_ingestion_alert_rule.py
  backend/deepchecks_monitoring/api/v1/global_api/organization.py
  backend/deepchecks_monitoring/bgtasks/model_data_ingestion_alerter.py
  backend/deepchecks_monitoring/bgtasks/scheduler.py
  backend/deepchecks_monitoring/config.py
  backend/deepchecks_monitoring/schema_migrations/versions/e8cb07203dd5_data_ingestion_alert.py
  backend/deepchecks_monitoring/schema_models/__init__.py
  backend/deepchecks_monitoring/schema_models/alert_rule.py
  backend/deepchecks_monitoring/schema_models/alert_webhook.py
  backend/deepchecks_monitoring/schema_models/data_ingestion_alert.py
  backend/deepchecks_monitoring/schema_models/data_ingestion_alert_rule.py
  backend/deepchecks_monitoring/schema_models/model.py
  backend/deepchecks_monitoring/schema_models/monitor.py
  backend/deepchecks_monitoring/utils/alerts.py
  backend/tests/api/test_alert_rules.py
  backend/tests/common.py
  backend/tests/unittests/test_model_data_ingestion_alerts.py
Labels: enhancement

#184 Fix user readd
  backend/deepchecks_monitoring/api/v1/global_api/users.py
  backend/tests/api/test_organization_api.py
Labels: bug

#186 fix installation link in docs
  docs/source/installation/self_host.rst
Labels: documentation

#185 Fix schema name too long
  backend/deepchecks_monitoring/public_models/organization.py
Labels: bug

#188 Fix accidental change
  backend/deepchecks_monitoring/api/v1/configuration.py
  backend/tests/api/test_alert_rules.py
Labels: bug

#192 Fix codgen
  backend/deepchecks_monitoring/api/v1/data_ingestion_alert_rule.py
  frontend/src/api/generated.ts
Labels: bug

#193 analysis filters validity check
  frontend/src/components/Analysis/AnalysisFilters/AnalysisFilters.helpers.ts
Labels: bug, invalid

#206 use parallel check executors in oss
  backend/deepchecks_monitoring/api/v1/monitor.py
  backend/deepchecks_monitoring/ee/resources.py
  deploy/oss-conf.env
Labels: bug

#211 assign models dialog data of the last update fix
  frontend/src/components/WorkspaceSettings/components/Members/members.constants.ts
Labels: invalid

#227 Terms and conditions removal
  bin/casbin_conf/init_data/init_data.json.tmpl
Labels: enhancement

#209 models only available if model_assignment is true
  frontend/src/components/WorkspaceSettings/WorkspaceSettings.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/MembersTable/MembersTable.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/MembersTable/MembersTableHead.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/MembersTable/MembersTableRow.tsx
  frontend/src/helpers/hooks/useUser.tsx
Labels: enhancement

#208 [DOCS] analysis page update
  docs/source/_static/images/user-guide/user_interface/6_Analysis.png
  docs/source/_static/images/user-guide/user_interface/6_Analysis_data_comparison.png
  docs/source/_static/images/user-guide/user_interface/6_Analysis_drilldown.png
  docs/source/_static/images/user-guide/user_interface/6_Analysis_filters_1.png
  docs/source/_static/images/user-guide/user_interface/6_Analysis_filters_2.png
  docs/source/user-guide/user_interface/analysis.rst
Labels: enhancement

#242 refresh monitors every 1 minute
  frontend/src/helpers/base/time.tsx
  frontend/src/helpers/hooks/useDataIngestion.tsx
  frontend/src/pages/DashboardPage.tsx
Labels: enhancement

#249 model-assignment check only when flag
  backend/deepchecks_monitoring/api/v1/alert.py
  backend/deepchecks_monitoring/api/v1/alert_rule.py
  backend/deepchecks_monitoring/api/v1/check.py
  backend/deepchecks_monitoring/api/v1/configuration.py
  backend/deepchecks_monitoring/api/v1/data_ingestion_alert.py
  backend/deepchecks_monitoring/api/v1/data_input.py
  backend/deepchecks_monitoring/api/v1/model.py
  backend/deepchecks_monitoring/api/v1/model_version.py
  backend/deepchecks_monitoring/api/v1/monitor.py
  backend/deepchecks_monitoring/schema_models/alert.py
  backend/deepchecks_monitoring/schema_models/alert_rule.py
  backend/deepchecks_monitoring/schema_models/check.py
  backend/deepchecks_monitoring/schema_models/data_ingestion_alert.py
  backend/deepchecks_monitoring/schema_models/data_ingestion_alert_rule.py
  backend/deepchecks_monitoring/schema_models/ingestion_errors.py
  backend/deepchecks_monitoring/schema_models/model.py
  backend/deepchecks_monitoring/schema_models/model_version.py
  backend/deepchecks_monitoring/schema_models/monitor.py
  backend/deepchecks_monitoring/schema_models/permission_mixin.py
Labels: bug

#254 put feature drift higher
  backend/deepchecks_monitoring/api/v1/check.py
Labels: enhancement

#246 [MON-2302] mixpanel server side events
  .github/workflows/e2e-tests.yml
  Dockerfile
  backend/deepchecks_monitoring/api/v1/alert_rule.py
  backend/deepchecks_monitoring/api/v1/data_input.py
  backend/deepchecks_monitoring/api/v1/global_api/auth.py
  backend/deepchecks_monitoring/api/v1/global_api/organization.py
  backend/deepchecks_monitoring/api/v1/model.py
  backend/deepchecks_monitoring/api/v1/model_version.py
  backend/deepchecks_monitoring/app.py
  backend/deepchecks_monitoring/bgtasks/alert_task.py
  backend/deepchecks_monitoring/bgtasks/mixpanel_system_state_event.py
  backend/deepchecks_monitoring/bgtasks/tasks_queuer.py
  backend/deepchecks_monitoring/bgtasks/tasks_runner.py
  backend/deepchecks_monitoring/config.py
  backend/deepchecks_monitoring/ee/bgtasks/object_storage_ingestor.py
  backend/deepchecks_monitoring/ee/config.py
  backend/deepchecks_monitoring/public_models/organization.py
  backend/deepchecks_monitoring/public_models/role.py
  backend/deepchecks_monitoring/public_models/user.py
  backend/deepchecks_monitoring/resources.py
  backend/deepchecks_monitoring/schema_models/model.py
  backend/deepchecks_monitoring/utils/mixpanel.py
  backend/requirements.txt
  backend/spelling-allowlist.txt
  backend/tests/conftest.py
Labels: enhancement

#260 mixpanel events - hot fix
  backend/deepchecks_monitoring/utils/mixpanel.py
Labels: bug

#231 [MON-2402] added integrations docs
  docs/source/_static/images/user-guide/user_interface/8.1.1_example_of_email_notification.png
  docs/source/_static/images/user-guide/user_interface/8.1.1_selection_of_alert_severity_for_email_notifications.png
  docs/source/_static/images/user-guide/user_interface/8.1.2_example_of_slack_message.png
  docs/source/_static/images/user-guide/user_interface/8.1.2_selection_of_alert_severity_for_slack_notifications.png
  docs/source/_static/images/user-guide/user_interface/8.1.2_slack_app_authorization.png
  docs/source/_static/images/user-guide/user_interface/8.1.2_slack_app_installation.png
  docs/source/_static/images/user-guide/user_interface/8.1.2_slack_app_installation_result.png
  docs/source/_static/images/user-guide/user_interface/8.1.3_selection_of_alert_severity_for_webhook.png
  docs/source/_static/images/user-guide/user_interface/8.1.3_webhook_creation.png
  docs/source/_static/images/user-guide/user_interface/8.1.3_webhook_creation_form.png
  docs/source/user-guide/index.rst
  docs/source/user-guide/user_interface/integrations.rst
Labels: documentation

#263 mixpanel user event - bug fix
  backend/deepchecks_monitoring/utils/mixpanel.py
Labels: bug

#223 [MON-2360] Monitor drawer migration to the new design
  frontend/src/components/Alerts/AlertRuleDialog/AlertRuleDialog.tsx
  frontend/src/components/Alerts/AlertRuleDialog/components/AlertRuleDialogContent.tsx
  frontend/src/components/Alerts/AlertRuleDialog/components/RuleDialogStepThree.tsx
  frontend/src/components/Alerts/AlertRuleDialog/components/RuleDialogStepTwo.tsx
  frontend/src/components/Dashboard/Dashboard.types.ts
  frontend/src/components/Dashboard/MonitorDialog/MonitorDialog.tsx
  frontend/src/components/Dashboard/MonitorDialog/components/ActiveAlertsModal.tsx
  frontend/src/components/Dashboard/MonitorDialog/components/CreateAlertForm/CreateAlertForm.helpers.ts
  frontend/src/components/Dashboard/MonitorDialog/components/CreateAlertForm/CreateAlertForm.tsx
  frontend/src/components/Dashboard/MonitorDialog/components/CreateAlertForm/SelectCondition.tsx
  frontend/src/components/Dashboard/MonitorDialog/components/CreateAlertForm/index.ts
  frontend/src/components/Dashboard/MonitorDialog/components/MonitorDialogGraph.tsx
  frontend/src/components/Dashboard/MonitorDialog/components/MonitorForm/MonitorForm.helpers.ts
  frontend/src/components/Dashboard/MonitorDialog/components/MonitorForm/MonitorForm.tsx
  frontend/src/components/Dashboard/MonitorDialog/components/MonitorForm/MonitorForm.types.ts
  frontend/src/components/Dashboard/MonitorDialog/components/MonitorForm/components/MonitorFormAdvancedSection.tsx
  frontend/src/components/Dashboard/MonitorDialog/components/MonitorForm/components/MonitorFormStepOne.tsx
  frontend/src/components/Dashboard/MonitorDialog/components/MonitorForm/components/MonitorFormStepTwo.tsx
  frontend/src/components/Dashboard/MonitorDialog/components/MonitorForm/components/MonitorFormSteps.tsx
  frontend/src/components/Dashboard/MonitorDialog/components/MonitorForm/index.ts
  frontend/src/components/Dashboard/MonitorDialog/index.ts
  frontend/src/components/Dashboard/MonitorDialog/monitorDialog.constants.ts
  frontend/src/components/Dashboard/MonitorDrawer/MonitorDrawer.tsx
  frontend/src/components/Dashboard/MonitorDrawer/components/CreateAlertForm/CreateAlertForm.tsx
  frontend/src/components/Dashboard/MonitorDrawer/components/MonitorForm/MonitorForm.style.tsx
  frontend/src/components/Dashboard/MonitorDrawer/components/MonitorForm/MonitorForm.tsx
  frontend/src/components/Dashboard/MonitorDrawer/index.ts
  frontend/src/components/Dashboard/MonitorList/MonitorList.tsx
  frontend/src/components/Dashboard/MonitorList/components/GraphicsSection/GraphicsSection.tsx
  frontend/src/components/Dashboard/MonitorList/components/GraphicsSection/components/RootMenu.tsx
  frontend/src/components/Dashboard/MonitorList/components/Monitor.tsx
  frontend/src/components/Dashboard/MonitorList/components/MonitorsGroup.tsx
  frontend/src/components/Dashboard/MonitorListHeader/MonitorListHeader.tsx
  frontend/src/components/Select/SelectCheck.tsx
  frontend/src/components/Select/SelectColumn.tsx
  frontend/src/components/Subcategory.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/DeleteWorkspaceDialog.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/EditMember.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/InviteMember.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/MembersActionDialogContentLayout.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/MembersActionDialogInput.tsx
  frontend/src/components/base/InputDropdown/ControlledBaseDropdown.tsx
  frontend/src/components/base/InputDropdown/InputDropdown.styles.tsx
  frontend/src/components/base/InputDropdown/InputDropdown.tsx
  frontend/src/components/base/RangePicker/RangePicker.tsx
  frontend/src/components/lib/components/Dialog/Dialog.tsx
  frontend/src/components/lib/theme/typography.ts
  frontend/src/pages/DashboardPage.tsx
Labels: enhancement

#264 update-tag
  backend/VERSION
Labels: enhancement

#265 Task queuer - retry interval per task
  backend/deepchecks_monitoring/bgtasks/mixpanel_system_state_event.py
  backend/deepchecks_monitoring/bgtasks/tasks_queuer.py
  backend/deepchecks_monitoring/public_models/task.py
Labels: enhancement

#268 [DOCS] Update installation and links
  docs/source/_static/images/sphinx_thumbnails/quickstarts/prepare-data-guide-book.png
  docs/source/_static/images/sphinx_thumbnails/quickstarts/prepare-data-guide-white.png
  docs/source/_static/images/sphinx_thumbnails/quickstarts/tabular-quickstart-rocket.png
  docs/source/_static/images/sphinx_thumbnails/quickstarts/tabular_quickstart_gray.png
  docs/source/getting-started/deploy_self_host_open_source.rst
  docs/source/user-guide/tabular/quickstarts/plot_prepare_your_data.py
  docs/source/user-guide/tabular/quickstarts/plot_quickstart.py
Labels: documentation

#272 email_enabled_flag_fix
  backend/deepchecks_monitoring/features_control.py
Labels: bug

#214 rbac + ec2 documentation
  docs/source/_static/images/user-guide/general/2.1_workspace.png
  docs/source/_static/images/user-guide/general/assign_models.png
  docs/source/_static/images/user-guide/general/assign_users.png
  docs/source/_static/images/user-guide/general/edit_user.png
  docs/source/_static/images/user-guide/general/invite_users.png
  docs/source/user-guide/general/deploying_on_ec2.rst
  docs/source/user-guide/general/workspace_and_users.rst
  docs/source/user-guide/general/workspace_settings.rst
  docs/source/user-guide/index.rst
Labels: documentation

#270 mixpanel events - small refactoring
  backend/deepchecks_monitoring/api/v1/data_input.py
  backend/deepchecks_monitoring/app.py
  backend/deepchecks_monitoring/bgtasks/mixpanel_system_state_event.py
  backend/deepchecks_monitoring/resources.py
  backend/deepchecks_monitoring/utils/mixpanel.py
  deploy/oss-conf.env
Labels: bug

#274 ray - temporary fix for OOM
  bin/start.sh
Labels: bug

#276 analysis page no models available case
  frontend/src/components/NoResults.tsx
  frontend/src/pages/AnalysisPage.tsx
Labels: bug, invalid

#277 mixpanel - hotfix
  backend/deepchecks_monitoring/utils/mixpanel.py
Labels: bug

#280 fix_members_sort
  backend/deepchecks_monitoring/public_migrations/versions/6dc7e5b8a608_fix_role_order.py
  frontend/src/components/WorkspaceSettings/components/Members/Members.tsx
  frontend/src/components/WorkspaceSettings/components/ModelsTab/components/ModelsTabTable/ModelsTabTable.tsx
  frontend/src/components/WorkspaceSettings/useOrganizationMembers.tsx
Labels: bug

#281 client operator name fix
  backend/client/deepchecks_client/core/utils.py
  backend/deepchecks_monitoring/monitoring_utils.py
Labels: bug

#283 fix_error_level_for_s3
  backend/deepchecks_monitoring/ee/bgtasks/object_storage_ingestor.py
Labels: bug

#285 AnalysisItem MultiSelect fix
  frontend/src/components/Analysis/AnalysisItem/components/AnalysisChartItemWithFilters/AnalysisItemSelect/MultiSelect.tsx
Labels: bug

#282 fix owner can remove itself when only owner
  backend/deepchecks_monitoring/ee/api/v1/members.py
Labels: bug

#288 DataIngestion time labels fix
  frontend/src/components/Dashboard/DataIngestion/DataIngestion.tsx
  frontend/src/components/Dashboard/MonitorList/components/GraphicsSection/GraphicsSection.style.tsx
  frontend/src/components/Dashboard/MonitorList/components/GraphicsSection/GraphicsSection.tsx
Labels: invalid

#289 git docker push test
  .github/workflows/e2e-tests.yml
  frontend/yarn.lock
Labels: enhancement

#290 [MON-2358] Open analysis drill down from the monitoring screen
  frontend/src/components/Analysis/AnalysisGroupBy/components/index.ts
  frontend/src/components/Analysis/AnalysisGroupBy/index.ts
  frontend/src/components/Analysis/AnalysisItem/AnalysisItem.tsx
  frontend/src/components/AnalysisDrillDown/AnalysisDrillDown.helpers.ts
  frontend/src/components/AnalysisDrillDown/AnalysisDrillDown.tsx
  frontend/src/components/AnalysisDrillDown/AnalysisDrillDown.types.ts
  frontend/src/components/AnalysisDrillDown/AnalysisDrillDownInfo/AnalysisDrillDownInfo.tsx
  frontend/src/components/AnalysisDrillDown/AnalysisDrillDownInfo/AnalysisDrillDownInfoItem.tsx
  frontend/src/components/AnalysisDrillDown/AnalysisDrillDownInfo/index.ts
  frontend/src/components/AnalysisDrillDown/index.ts
  frontend/src/components/Dashboard/ModelList/ModelList.tsx
  frontend/src/components/Dashboard/MonitorList/MonitorList.tsx
  frontend/src/components/Dashboard/MonitorList/components/GraphicsSection/GraphicsSection.tsx
  frontend/src/components/Dashboard/MonitorList/components/Monitor.tsx
  frontend/src/components/Dashboard/MonitorList/components/MonitorsGroup.tsx
  frontend/src/components/SegmentsDrillDown/SegmentsDrillDown.tsx
  frontend/src/pages/AnalysisPage.tsx
  frontend/src/pages/DashboardPage.tsx
Labels: enhancement
