Repository deepchecks/monitoring, pull requests merged in 2023-05, with the labels that each got.

#50 fix slack notifications
  backend/deepchecks_monitoring/ee/integrations/slack.py
Labels: bug

#52 sentry issues
  frontend/src/components/DiagramLine/DiagramLine.tsx
  frontend/src/components/WorkspaceSettings/Billing/BillingPaymentWrapper.tsx
  frontend/src/components/WorkspaceSettings/WorkspaceSettings.tsx
  frontend/src/helpers/utils/parseDataForChart.ts
Labels: bug

#54 weird slider filter logic fix
  frontend/src/components/Analysis/AnalysisFilters/components/NumericFilter.tsx
Labels: invalid

#58 Adding flag to control parallelism
  .github/workflows/license-check.yml
  backend/deepchecks_monitoring/api/v1/check.py
  backend/deepchecks_monitoring/api/v1/monitor.py
  backend/deepchecks_monitoring/bgtasks/actors.py
  backend/deepchecks_monitoring/config.py
Labels: enhancement

#59 Jonatan/mon 2012 be onboarding implementation
  backend/client/deepchecks_client/core/api.py
  backend/client/deepchecks_client/core/client.py
  backend/client/deepchecks_client/core/utils.py
  backend/deepchecks_monitoring/api/v1/__init__.py
  backend/deepchecks_monitoring/api/v1/onboarding.py
  backend/load_tests/locustfile.py
  backend/tests/api/test_onboarding.py
  frontend/src/api/generated.ts
Labels: enhancement

#57 errors fix
  frontend/src/components/Dashboard/ModelList/ModelList.tsx
  frontend/src/components/Dashboard/ModelList/components/ModelItem/ModelItem.style.tsx
  frontend/src/components/Dashboard/MonitorList/MonitorList.tsx
  frontend/src/components/Dashboard/MonitorList/components/GraphicsSection/components/MonitorAlertRuleWidget/MonitorAlertRuleWidget.style.tsx
  frontend/src/components/Dashboard/MonitorList/components/GraphicsSection/components/MonitorAlertRuleWidget/MonitorAlertRuleWidget.tsx
  frontend/src/components/DiagramLine/DiagramLine.tsx
  frontend/src/components/Layout/Sidebar/Sidebar.tsx
  frontend/src/components/WorkspaceSettings/Billing/Billing.tsx
  frontend/src/components/WorkspaceSettings/Billing/BillingPaymentWrapper.tsx
  frontend/src/components/lib/components/Container/Container.tsx
  frontend/src/helpers/hooks/useDataIngestion.tsx
  frontend/src/pages/AlertRules.tsx
  frontend/src/pages/AlertsPage.tsx
  frontend/src/pages/ModelsPage.tsx
Labels: bug

#62 fix incompatible check type error
  backend/deepchecks_monitoring/api/v1/check.py
  backend/deepchecks_monitoring/logic/model_logic.py
Labels: bug

#45 raise alert on the number of samples
  backend/deepchecks_monitoring/bgtasks/delete_db_table_task.py
  backend/deepchecks_monitoring/bgtasks/model_data_ingestion_alerter.py
  backend/deepchecks_monitoring/bgtasks/model_version_cache_invalidation.py
  backend/deepchecks_monitoring/bgtasks/model_version_offset_update.py
  backend/deepchecks_monitoring/bgtasks/model_version_topic_delete.py
  backend/deepchecks_monitoring/bgtasks/scheduler.py
  backend/deepchecks_monitoring/bgtasks/tasks_runner.py
  backend/deepchecks_monitoring/logic/model_logic.py
  backend/deepchecks_monitoring/public_models/task.py
  backend/deepchecks_monitoring/schema_migrations/versions/9b75d4bf2ee1_model_data_ingestion_alert.py
  backend/deepchecks_monitoring/schema_models/__init__.py
  backend/deepchecks_monitoring/schema_models/data_ingestion_alert.py
  backend/deepchecks_monitoring/schema_models/model.py
  backend/tests/unittests/test_model_data_ingestion_alerts.py
Labels: enhancement

#71 labels date fix
  frontend/src/components/Analysis/AnalysisGroupBy/AnalysisGroupBy.tsx
  frontend/src/components/DiagramLine/DiagramLine.tsx
Labels: bug

#61 Workspace settings page restyling
  frontend/src/components/WorkspaceSettings/Members/components/MembersHeader.tsx
  frontend/src/components/WorkspaceSettings/Members/components/MembersTable/MembersTable.style.tsx
  frontend/src/components/WorkspaceSettings/Members/components/MembersTable/MembersTable.tsx
  frontend/src/components/WorkspaceSettings/Members/components/MembersTable/MembersTableRow.tsx
  frontend/src/components/WorkspaceSettings/WorkspaceSettings.tsx
Labels: enhancement

#74 MON-2153 fe rbac implement permission control
  frontend/src/components/Notifications/AlertNotifications.tsx
  frontend/src/helpers/permissionControl.tsx
  frontend/src/pages/DashboardPage.tsx
  frontend/src/pages/IntegrationsPage.tsx
Labels: enhancement

#75 add-delete-method-to-organization
  backend/deepchecks_monitoring/api/v1/global_api/organization.py
  backend/deepchecks_monitoring/utils/auth.py
  frontend/src/api/generated.ts
Labels: bug

#76 dialog window text align fix
  frontend/src/components/lib/components/Dialog/DeletionDialog/DeletionDialog.tsx
  frontend/src/components/lib/components/Dialog/Dialog.tsx
Labels: bug

#77 fix links
  backend/deepchecks_monitoring/schema_models/check.py
  backend/tests/api/test_monitor.py
Labels: bug

#79 Fixing cypress tests
  backend/deepchecks_monitoring/public_models/organization.py
  cypress/e2e/alert_rules_screen.cy.ts
  cypress/e2e/connected_models_screen.cy.ts
  docker-compose.yml
  frontend/src/components/Alerts/AlertRuleDialog/AlertRuleDialog.tsx
Labels: enhancement

#81 fix instrumentation for workers
  backend/deepchecks_monitoring/bgtasks/tasks_runner.py
  backend/deepchecks_monitoring/ee/utils/telemetry.py
  backend/tests/unittests/conftest.py
Labels: bug

#84 extend settings for runner
  backend/deepchecks_monitoring/bgtasks/tasks_runner.py
Labels: bug

#83 add roles to backend
  backend/deepchecks_monitoring/api/v1/global_api/organization.py
  backend/deepchecks_monitoring/api/v1/global_api/users.py
  backend/deepchecks_monitoring/ee/api/v1/billing.py
  backend/deepchecks_monitoring/ee/middlewares.py
  backend/deepchecks_monitoring/public_migrations/versions/57a5a7543c41_user_roles.py
  backend/deepchecks_monitoring/public_models/__init__.py
  backend/deepchecks_monitoring/public_models/organization.py
  backend/deepchecks_monitoring/public_models/role.py
  backend/deepchecks_monitoring/public_models/user.py
  backend/deepchecks_monitoring/utils/auth.py
  backend/deepchecks_monitoring/utils/other.py
  backend/tests/api/test_organization_api.py
  backend/tests/common.py
  backend/tests/unittests/test_user_creation.py
  frontend/src/api/generated.ts
  frontend/src/components/WorkspaceSettings/WorkspaceSettings.tsx
  frontend/src/helpers/hooks/useUser.tsx
Labels: enhancement

#70 Deepchecks addons
  Dockerfile
  backend/addon-requirements.txt
  backend/deepchecks_monitoring/api/v1/check.py
  backend/deepchecks_monitoring/logic/check_logic.py
  backend/deepchecks_monitoring/schema_models/check.py
Labels: enhancement

#87 [MON-2205] standard webhooks execution refactoring
  backend/deepchecks_monitoring/monitoring_utils.py
  backend/deepchecks_monitoring/schema_models/alert_rule.py
  backend/deepchecks_monitoring/schema_models/alert_webhook.py
  backend/tests/unittests/test_alert_webhooks.py
Labels: enhancement

#86 Fix session not rolled back in scheduler
  backend/deepchecks_monitoring/bgtasks/scheduler.py
Labels: bug

#88 fix for alert-rules config
  backend/deepchecks_monitoring/api/v1/configuration.py
  backend/deepchecks_monitoring/api/v1/global_api/users.py
  backend/tests/api/test_alert_rules.py
Labels: bug

#93 add more info to /connected-models
  backend/deepchecks_monitoring/api/v1/model.py
  backend/deepchecks_monitoring/bgtasks/model_data_ingestion_alerter.py
  backend/tests/api/test_models.py
  backend/tests/common.py
  frontend/.env.development
  frontend/src/api/generated.ts
  frontend/src/components/Dashboard/ModelList/ModelList.tsx
  frontend/src/pages/ModelsPage.tsx
Labels: enhancement

#92 Webhooks - additional tests, fixes, refactoring
  backend/client/deepchecks_client/core/api.py
  backend/deepchecks_monitoring/api/v1/alert_webhooks.py
  backend/deepchecks_monitoring/schema_migrations/versions/021d60e962f4_fix_webhookkind_enum.py
  backend/deepchecks_monitoring/schema_models/alert_webhook.py
  backend/tests/api/test_alert_webhooks.py
  backend/tests/common.py
  backend/tests/unittests/test_alert_notificator.py
  backend/tests/unittests/test_alert_webhooks.py
  backend/tests/utils.py
Labels: enhancement

#94 [MON-2240] more data on the model item
  frontend/src/components/ModelInfoItem/ModelInfoItem.style.tsx
  frontend/src/components/ModelInfoItem/ModelInfoItem.tsx
  frontend/src/components/ModelInfoItem/components/FooterItem.tsx
  frontend/src/pages/ModelsPage.tsx
Labels: enhancement

#95 Update roles endpoint
  backend/deepchecks_monitoring/ee/api/v1/__init__.py
  backend/deepchecks_monitoring/ee/api/v1/members.py
  backend/deepchecks_monitoring/ee/features_control.py
  backend/deepchecks_monitoring/features_control.py
  backend/tests/api/test_alert_rules.py
  backend/tests/api/test_users_api.py
  backend/tests/conftest.py
  frontend/src/api/generated.ts
Labels: enhancement

#90 [MON-1817] fe rbac redesign members & add deletion org functionality
  frontend/src/components/Layout/Sidebar/components/UserInfo/UserInfo.tsx
  frontend/src/components/WorkspaceSettings/Members/Members.tsx
  frontend/src/components/WorkspaceSettings/Members/Members.type.ts
  frontend/src/components/WorkspaceSettings/Members/components/DeleteWorkspace.tsx
  frontend/src/components/WorkspaceSettings/Members/components/DeleteWorkspaceDialog.tsx
  frontend/src/components/WorkspaceSettings/Members/components/EditMember.tsx
  frontend/src/components/WorkspaceSettings/Members/components/MembersActionDialogInput.tsx
  frontend/src/components/WorkspaceSettings/Members/components/MembersHeader.tsx
  frontend/src/components/WorkspaceSettings/Members/components/MembersListActionDialog.tsx
  frontend/src/components/WorkspaceSettings/Members/components/MembersTable/MembersTable.style.tsx
  frontend/src/components/WorkspaceSettings/Members/components/MembersTable/MembersTable.tsx
  frontend/src/components/WorkspaceSettings/Members/components/MembersTable/MembersTableHead.tsx
  frontend/src/components/WorkspaceSettings/Members/components/MembersTable/MembersTableRow.tsx
  frontend/src/components/WorkspaceSettings/Members/components/RemoveMember.tsx
  frontend/src/components/WorkspaceSettings/Members/components/RemoveSelectedMembers.tsx
  frontend/src/components/WorkspaceSettings/Members/members.constants.ts
  frontend/src/components/lib/components/Button/Checkbox/Checkbox.tsx
  frontend/src/components/lib/theme/typography.ts
Labels: enhancement

#96 add run permissions to bin
  bin/start-task-queuer.sh
  bin/start-task-runner.sh
Labels: bug

#97 Fix roles
  backend/deepchecks_monitoring/ee/api/v1/members.py
  frontend/src/api/generated.ts
Labels: bug

#100 AnalysisItem multiselect dropdown fix
  frontend/src/components/Analysis/AnalysisItem/components/AnalysisChartItemWithFilters/AnalysisItemSelect/MultiSelect.tsx
  frontend/src/components/Analysis/AnalysisItem/components/AnalysisChartItemWithFilters/AnalysisItemSelect/components/InputLabel.tsx
Labels: bug

#99 resolve alert message fix
  frontend/src/components/Alerts/AlertResolveDialog/AlertResolveDialog.style.ts
  frontend/src/components/Alerts/AlertResolveDialog/AlertResolveDialog.tsx
  frontend/src/pages/AlertsPage.tsx
Labels: invalid

#98 [MON-1965] fe rbac ui for changing role on members
  frontend/src/components/WorkspaceSettings/Members/Members.tsx
  frontend/src/components/WorkspaceSettings/Members/components/DeleteWorkspace.tsx
  frontend/src/components/WorkspaceSettings/Members/components/EditMember.tsx
  frontend/src/components/WorkspaceSettings/Members/components/MembersActionDialogInput.tsx
  frontend/src/components/WorkspaceSettings/Members/components/MembersHeader.tsx
  frontend/src/components/WorkspaceSettings/Members/components/RemoveSelectedMembers.tsx
  frontend/src/components/WorkspaceSettings/Members/members.constants.ts
  frontend/src/components/lib/components/Dropdown/Dropdown.tsx
  frontend/src/components/lib/components/Input/Input.tsx
  frontend/src/helpers/hooks/useUser.tsx
Labels: enhancement

#102 [MON-2252] slack app multiple redirect urls fix
  backend/deepchecks_monitoring/ee/api/v1/slack.py
  backend/deepchecks_monitoring/ee/integrations/slack.py
  backend/tests/api/test_slack_integration.py
Labels: bug

#108 Slack integration card duplicated text fix
  frontend/src/components/Integrations/ConnectSlack.tsx
Labels: bug

#101 AlertsDrawer share button lead to specific alert
  frontend/src/components/SegmentsDrillDown/SegmentsDrillDown.tsx
  frontend/src/pages/AlertsPage.tsx
Labels: enhancement

#106 alert rule dialog layout fix
  frontend/src/components/Alerts/AlertRuleDialog/components/RuleDialogStepThree.tsx
Labels: bug

#107 delete model logic fix
  frontend/src/components/ModelInfoItem/ModelInfoItem.tsx
  frontend/src/pages/ModelsPage.tsx
Labels: bug

#105 redirect to login on invalid claim
  backend/deepchecks_monitoring/api/v1/global_api/auth.py
Labels: bug

#120 Fix redirect on invalid claim
  backend/deepchecks_monitoring/api/v1/global_api/auth.py
Labels: bug

#110 missing label % calculation fix
  frontend/src/components/ModelInfoItem/ModelInfoItem.tsx
Labels: invalid

#121 Jonatan/mon 2238 be add user per model
  backend/deepchecks_monitoring/api/v1/alert.py
  backend/deepchecks_monitoring/api/v1/alert_rule.py
  backend/deepchecks_monitoring/api/v1/check.py
  backend/deepchecks_monitoring/api/v1/data_input.py
  backend/deepchecks_monitoring/api/v1/e2e_support_api.py
  backend/deepchecks_monitoring/api/v1/global_api/users.py
  backend/deepchecks_monitoring/api/v1/model.py
  backend/deepchecks_monitoring/api/v1/model_version.py
  backend/deepchecks_monitoring/api/v1/monitor.py
  backend/deepchecks_monitoring/config.py
  backend/deepchecks_monitoring/ee/api/v1/members.py
  backend/deepchecks_monitoring/ee/features_control.py
  backend/deepchecks_monitoring/features_control.py
  backend/deepchecks_monitoring/notifications.py
  backend/deepchecks_monitoring/public_models/organization.py
  backend/deepchecks_monitoring/schema_migrations/versions/1b0028e8c1e1_model_members.py
  backend/deepchecks_monitoring/schema_models/__init__.py
  backend/deepchecks_monitoring/schema_models/alert.py
  backend/deepchecks_monitoring/schema_models/alert_rule.py
  backend/deepchecks_monitoring/schema_models/check.py
  backend/deepchecks_monitoring/schema_models/ingestion_errors.py
  backend/deepchecks_monitoring/schema_models/model.py
  backend/deepchecks_monitoring/schema_models/model_memeber.py
  backend/deepchecks_monitoring/schema_models/model_version.py
  backend/deepchecks_monitoring/schema_models/monitor.py
  backend/deepchecks_monitoring/schema_models/permission_mixin.py
  backend/deepchecks_monitoring/utils/alerts.py
  backend/deepchecks_monitoring/utils/auth.py
  backend/tests/api/test_alert_rules.py
  backend/tests/api/test_models.py
  backend/tests/api/test_users_api.py
  backend/tests/common.py
  backend/tests/conftest.py
  backend/tests/unittests/test_alert_notificator.py
  backend/tests/unittests/test_alert_webhooks.py
  backend/tests/utils.py
  frontend/src/api/generated.ts
  frontend/src/components/ModelInfoItem/components/ModalItemViewDetails/components/ModelDetails/components/ModelNotes/ModelNotes.tsx
Labels: enhancement

#125 login screen image update
  frontend/src/assets/bg/backgrounds.ts
  frontend/src/assets/bg/loginScreenImage.svg
  frontend/src/pages/CompleteDetails.tsx
Labels: invalid

#124 [mon-1885] unacceptable performance: parallelize data retrieval (replaces joblib with ray)
  .github/workflows/pylint.yml
  backend/deepchecks_monitoring/api/v1/check.py
  backend/deepchecks_monitoring/app.py
  backend/deepchecks_monitoring/config.py
  backend/deepchecks_monitoring/ee/resources.py
  backend/deepchecks_monitoring/logic/check_logic.py
  backend/deepchecks_monitoring/logic/model_logic.py
  backend/deepchecks_monitoring/logic/parallel_check_executor.py
  backend/deepchecks_monitoring/logic/suite_logic.py
  backend/deepchecks_monitoring/resources.py
  backend/deepchecks_monitoring/schema_models/model_version.py
  backend/deepchecks_monitoring/utils/auth.py
  backend/deepchecks_monitoring/utils/notebook_util.py
  backend/requirements.txt
  backend/spelling-allowlist.txt
  bin/start.sh
Labels: enhancement

#126 parallel check execution - logging
  backend/deepchecks_monitoring/app.py
  backend/deepchecks_monitoring/ee/resources.py
  backend/deepchecks_monitoring/resources.py
Labels: enhancement

#128 fix model_members migrations
  backend/deepchecks_monitoring/schema_migrations/versions/1b0028e8c1e1_model_members.py
  backend/deepchecks_monitoring/utils/database.py
Labels: bug

#122 fix logger
  backend/deepchecks_monitoring/middlewares.py
Labels: bug

#132 ray initialization - logging fix
  backend/deepchecks_monitoring/app.py
  backend/deepchecks_monitoring/ee/resources.py
  backend/deepchecks_monitoring/resources.py
  backend/spelling-allowlist.txt
Labels: bug

#133 [BUG] circular import error fix
  backend/deepchecks_monitoring/schema_models/permission_mixin.py
Labels: bug

#134 start script fix
  bin/start.sh
Labels: bug

#135 [MON-2296] webhooks instegration
  backend/deepchecks_monitoring/api/v1/global_api/organization.py
  backend/tests/api/test_organization_api.py
Labels: enhancement

#137 Parallel check executor - Idle session timeout fix
  backend/deepchecks_monitoring/ee/resources.py
  backend/deepchecks_monitoring/logic/parallel_check_executor.py
Labels: bug

#141 [BUG] Parallel check executor refactoring/fix
  backend/deepchecks_monitoring/logic/parallel_check_executor.py
Labels: bug

#116 [MON-2145] add models tab to enable assigning users permissions to
  frontend/src/components/Layout/Sidebar/Sidebar.tsx
  frontend/src/components/Layout/Sidebar/components/UserInfo/UserInfo.tsx
  frontend/src/components/WorkspaceSettings/WorkspaceSettings.helpers.ts
  frontend/src/components/WorkspaceSettings/WorkspaceSettings.styles.tsx
  frontend/src/components/WorkspaceSettings/WorkspaceSettings.tsx
  frontend/src/components/WorkspaceSettings/components/Billing/Billing.styles.tsx
  frontend/src/components/WorkspaceSettings/components/Billing/Billing.tsx
  frontend/src/components/WorkspaceSettings/components/Billing/BillingHistory/BillingHistory.tsx
  frontend/src/components/WorkspaceSettings/components/Billing/BillingHistory/BillingTransaction.tsx
  frontend/src/components/WorkspaceSettings/components/Billing/BillingMethods/BillingMethodDialog.tsx
  frontend/src/components/WorkspaceSettings/components/Billing/BillingMethods/BillingMethods.tsx
  frontend/src/components/WorkspaceSettings/components/Billing/BillingPaidView/BillingPaidSkeleton.tsx
  frontend/src/components/WorkspaceSettings/components/Billing/BillingPaidView/BillingPaidView.tsx
  frontend/src/components/WorkspaceSettings/components/Billing/BillingPaymentWrapper.tsx
  frontend/src/components/WorkspaceSettings/components/Billing/BillingPlanCard/BillingPlanCard.tsx
  frontend/src/components/WorkspaceSettings/components/Billing/BillingPlanCard/BillingPlanCardDialog.tsx
  frontend/src/components/WorkspaceSettings/components/Billing/FirstBilling/FirstBilling.tsx
  frontend/src/components/WorkspaceSettings/components/Billing/FirstBilling/FirstBillingPayment.tsx
  frontend/src/components/WorkspaceSettings/components/Billing/billing.constants.ts
  frontend/src/components/WorkspaceSettings/components/Billing/billing.types.ts
  frontend/src/components/WorkspaceSettings/components/DialogListItem.tsx
  frontend/src/components/WorkspaceSettings/components/Members/Members.tsx
  frontend/src/components/WorkspaceSettings/components/Members/Members.type.ts
  frontend/src/components/WorkspaceSettings/components/Members/components/AssignModels.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/DeleteWorkspace.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/DeleteWorkspaceDialog.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/EditMember.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/InviteMember.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/MembersActionDialogContentLayout.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/MembersActionDialogInput.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/MembersHeader.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/MembersListActionDialog.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/MembersTable/MembersTable.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/MembersTable/MembersTableHead.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/MembersTable/MembersTableRow.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/RemoveMember.tsx
  frontend/src/components/WorkspaceSettings/components/Members/components/RemoveSelectedMembers.tsx
  frontend/src/components/WorkspaceSettings/components/Members/members.constants.ts
  frontend/src/components/WorkspaceSettings/components/ModelsTab/ModelsTab.tsx
  frontend/src/components/WorkspaceSettings/components/ModelsTab/components/AssignMembersToModelDialog.tsx
  frontend/src/components/WorkspaceSettings/components/ModelsTab/components/ModelsTabHeader.tsx
  frontend/src/components/WorkspaceSettings/components/ModelsTab/components/ModelsTabTable/ModelsTabTable.tsx
  frontend/src/components/WorkspaceSettings/components/ModelsTab/components/ModelsTabTable/ModelsTabTableHead.tsx
  frontend/src/components/WorkspaceSettings/components/ModelsTab/components/ModelsTabTable/ModelsTabTableRow.tsx
  frontend/src/components/WorkspaceSettings/components/ModelsTab/modelsTab.constants.ts
  frontend/src/components/WorkspaceSettings/components/NotAdminDialog/NotAdminDialog.tsx
  frontend/src/components/WorkspaceSettings/useOrganizationMembers.tsx
  frontend/src/components/lib/components/Button/Button.tsx
  frontend/src/components/lib/theme/typography.ts
  frontend/src/helpers/hooks/useListSearchField.tsx
  frontend/src/helpers/hooks/useUser.tsx
Labels: enhancement

#146 alerts drawer fix
  frontend/src/components/Alerts/AlertsDrawer/components/AlertBadge.tsx
  frontend/src/components/Alerts/AlertsDrawer/components/AlertsDrawerDiagram.tsx
  frontend/src/components/Alerts/AlertsDrawer/components/AlertsDrawerHeader.tsx
  frontend/src/helpers/setGraphOptions.ts
Labels: bug

#150 Check execution actors - startup config fix
  backend/deepchecks_monitoring/app.py
  backend/deepchecks_monitoring/config.py
  backend/deepchecks_monitoring/logic/parallel_check_executor.py
  backend/deepchecks_monitoring/resources.py
Labels: bug

#148 dashboard data ingestion UI crash fix
  frontend/src/components/Dashboard/DataIngestion/DataIngestion.tsx
Labels: bug

#153 [MON-2343] check execution - bug fix
  backend/deepchecks_monitoring/logic/parallel_check_executor.py
Labels: bug

#158 fix_performance of /connected-models
  backend/deepchecks_monitoring/api/v1/model.py
Labels: bug
